//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _080220223
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public int BolumNo { get; set; }
        public string BolumAdi { get; set; }
        public Nullable<int> BolumUrunSayisi { get; set; }
        public Nullable<int> SorumluNo { get; set; }
    }
}
