//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _080220223
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sorumluluk
    {
        public int SorumlulukNo { get; set; }
        public Nullable<int> MagazaNo { get; set; }
        public string SorumluAdi { get; set; }
        public Nullable<decimal> SorumluMaas { get; set; }
        public Nullable<decimal> SorumluPrim { get; set; }
        public Nullable<int> SorumluVardiya { get; set; }
    }
}
